### PR TITLE
Fix children of driver buttons not triggering click events

### LINKED ISSUE #559: Children of footer buttons do not trigger click events
I am currently trying to inject Font Awesome icons into the "next" and "previous" buttons in `onPopoverRender`. This works fine visually, but when I click specifically on the icon, it does not trigger the click event of the surrounding button. So if I click on the icon inside the "next" button, nothing happens. Instead, the usual action of progressing to the next step should happen.

I have created a small example to reproduce it https://stackblitz.com/edit/vitejs-vite-3e85f2m9?file=src%2Fmain.js

I have also created PR #560 to fix this issue.

### PR DESCRIPTION
**Pull request by jarikmarwede**
Closes #559

### CODE REVIEW

File: src/popover.ts [hunk 1]
```diff
@@ -161,7 +161,17 @@ export function renderPopover(element: Element, step: DriveStep) {
...
-      if (target.classList.contains("driver-popover-next-btn")) {
+      const parentsClassListsContain = (element: HTMLElement, parentClass: string): boolean => {
+        if (element.classList.contains(parentClass)) {
+          return true;
+        }
+        if (element.parentElement !== null) {
+          return parentsClassListsContain(element.parentElement, parentClass);
+        }
+        return false;
+      };
```
Comment (jarikmarwede) [inline src/popover.ts:172]: Let me know if there is an easier way to do this or if the function should be located somewhere else in the project. I put it here because it is only used in this file, but maybe it should move to `utils.ts`

Comment (naren-innowell) [reply src/popover.ts:172]: I am trying to add a skip button using the following code:
The issue is that the Skip button is added, but the click event listener is not working. Can you also please check if this issue can also be addressed in your PR? Thank you.

`onPopoverRender: (popover) => {
    const skipButtonContainer = document.createElement("div");
    skipButtonContainer.classList.add('driver-popover-skip-btn-container');

    const skipButton = document.createElement("button");
    skipButton.innerText = "Skip";
    skipButton.classList.add('driver-popover-skip-btn');

    skipButtonContainer.appendChild(skipButton);
    popover.footerButtons.appendChild(skipButtonContainer);

    // Delay the event listener to ensure the button is fully rendered
    setTimeout(() => {
      skipButton.addEventListener("click", () => {
        console.log("Skip button clicked");
      });
    }, 0);
  },`

Comment (nabil-otsmane) [reply src/popover.ts:172]: @naren-innowell check this issue #565

File: src/popover.ts [hunk 2]
```diff
@@ -161,7 +161,17 @@ export function renderPopover(element: Element, step: DriveStep) {
...
+
+      if (parentsClassListsContain(target, "driver-popover-next-btn")) {
```
Comment (kamranahmedse) [inline src/popover.ts:174]: @jarikmarwede would it work if we [use `.closest`](https://developer.mozilla.org/en-US/docs/Web/API/Element/closest)? Because your utility will iterate all the way upto `body` which doesn't seem really performant.

```javascript
target.classList.contains("driver-popover-next-btn") ||  !!target.closest(".driver-popover-next-btn")
```

**Review by nilbuild — CHANGES_REQUESTED** [review]

File: src/popover.ts (hunk 2 above)
Comment (jarikmarwede) [reply src/popover.ts]: Yes, that's exactly the function I was looking for. We don't even need the first check in your example because the `closest` method also matches the element it is called on.
I don't exactly understand what is supposed to be more performant about it, because as far as I understand it also just traverses the DOM upwards until it matches an element or hits the root. But using a standard method for that is of course much nicer than creating a custom one.
I have removed my custom function and changed all the calls to `closest()`.
